title:            Marcos Rodrigues
description:      "Oddly Functional"
logo:             logo.png
disqus_shortname: mfprodrigues
share:            true
dropcap:      true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url: "https://www.oddlyfunctional.com"
default_bg: logo.png

# Owner/author information
owner:
  name:           Marcos Rodrigues
  avatar:         avatar.jpeg
  email:          hi@oddlyfunctional.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Ruby and JavaScript expert, teacher at Le Wagon, CTO at Santo Contrato, enthusiastic learner.
  # Social networking links used in footer. Update and remove as you like.
  twitter:        oddlyfunctional
  facebook:       oddlyfunctional
  github:         oddlyfunctional
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/105387902131919964437/

# Analytics and webmaster tools stuff goes here
google_analytics: UA-83052309-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: "home"
  - title: "Game Dev"
    url: "/gamedev"
    external: false
  - title: "CV"
    url: "/cv"
    external: false
  # - title: Featured Posts
  #   url: /featured
  # - title: Categories
  #   url: /categories
  # - title: About
  #   url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'https://oddlyfunctional.github.io/'
  relativeLinks: 'https://oddlyfunctional.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

cv:
  sections:
    - current_position
    - what_im_looking_for
    - specialized_in
    - skills
    - technologies
    - education
    - publications
    - experience

  jobs:
    - date: "Feb/2018 - Present"
      role: "Lead Fullstack Developer"
      techs: "Rails, React, Redux"
      company: "oduk.k.k."
      location: "Yokohama, Kanagawa, Japan"
      description: >
        Currently building a TripAdvisor-like application in a team of 2
        developers, focused on high-quality videos of venues and experiences in
        Japan, in preparation for the 2020 Olympics.

    - date: "Mar/2017 - Present"
      role: "CTO"
      techs: "Rails"
      company: "Santo Contrato Gestão Contratual"
      location: "Remote position"
      description: >
        Business partner in a lawtech company. Built alone a platform for
        managing legal documents, deadlines and other assets, with
        collaborative sharing, versioning, live chat, notifications and
        granular permissions system.

    - date: "Sep/2017 - Apr/2018"
      role: "Consulting and Development"
      techs: "Rails, React, Redux"
      company: "LanguagesSkills®"
      location: "São Paulo, Brazil"
      description: >
        Provided consulting sessions and built parts of a language-learning
        platform focused on specialized training for employees of
        organizations.

    - date: "Mar/2017 - Dec/2017"
      role: "Lead Teacher"
      company: "Le Wagon"
      location: "São Paulo, Brazil"
      description: >
        Teacher at an international coding bootcamp. Was responsible for
        lectures and one-on-one help. Due to my firmly grounded ability to
        answer questions and solve bugs, as well as the thoroughness of my
        explanations, several students sought me for mentoring, career advice
        and consulting on their startups.

    - date: "Jan/2016 - Jun/2016"
      role: "CTO"
      techs: "Rails, Angular"
      company: "Mozsaico"
      location: "Remote position"
      description: >
        Business partner from day zero in an edutech startup, developed a
        platform for managing and discussing content within organizations.
        Built the MVP alone, which included a web application and a Chrome
        extension.

    - date: "Dec/2015 - Apr/2018"
      role: "Online Consulting, Mentoring and Freelance"
      techs: "Ruby, Angular, React, Redux, Python, Azure Machine Learning, Meteor"
      description: >
        Provided consulting sessions on technology decisions, refactoring,
        software design and debugging, as well as mentoring and career advice.

    - date: "Feb/2014 - Dec/2015"
      role: "Lead Fullstack Developer"
      techs: "Rails, Angular"
      company: "Dunno"
      location: "Remote position"
      description: >
        Business partner in an edutech startup. Responsible for making
        technology decisions in a team of 2 engineers, building the project
        from scratch while working closely to the CEO to validate the product.
        The app was used by teachers and their students to organize content and
        collaborate on discussion topics, as well as by organizations to
        monitor their progress. It was my first time writing a SPA, and when I
        first started to learn more deeply JavaScript's foundations.

    - date: "Dec/2012 - Feb/2014"
      role: "Fullstack Developer"
      techs: "Rails, jQuery, AWS EC2"
      company: "Outra Coisa"
      location: "Rio de Janeiro, Brazil"
      description: >
        Maintained and wrote new features for production applications (audio
        clips marketplace and city guide) in a team of 4 developers. Was
        responsible for the Amazon EC2 server and the migration to Heroku.
        Strong emphasis in design, with pixel-perfect implementations.

    - date: "Jul/2010 - Oct/2011"
      role: "Fullstack Developer"
      techs: "Rails, jQuery"
      company: "STI"
      location: "Niterói, Brazil"
      description: >
        Developed from scratch a social network (team of 3) and a school
        administration system (team of 8) for a college. First job after
        learning Ruby on Rails, was part of a Scrum team in close contact with
        the client, performing requirements gathering and coding.

    - date: "Aug/2008 - May/2009"
      role: "Desktop Developer"
      techs: "Java"
      company: "LMDC"
      location: "Niterói, Brazil"
      description: >
        Desktop development for ERD application using javax.swing.
